-- ============================================================
-- ADD 62 FLOWERS - Australie (Hémisphère Sud)
-- Ce script ajoute 62 fleurs à la table seasonal_flowers existante
-- ON CONFLICT DO NOTHING évite les doublons avec les 8 fleurs déjà présentes
-- ============================================================

INSERT INTO seasonal_flowers (
  flower_name, scientific_name, common_names,
  seasons, peak_months, year_round,
  role, color_variants, bloom_size, texture,
  price_tier, availability_region, import_required,
  vase_life_days, fragrance_level, toxicity_warning,
  style_tags, notes
) VALUES

-- ============================================================
-- FOCAL FLOWERS (17)
-- ============================================================

('garden_rose',
 'Rosa x hybrida',
 ARRAY['Garden Rose', 'David Austin Rose', 'English Rose'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[10,11,12,1,2,3], TRUE,
 'focal', ARRAY['white', 'blush', 'cream', 'peach', 'coral', 'pink', 'red', 'burgundy', 'lilac'], 'large', 'layered_ruffled',
 'premium', 'australia_wide', FALSE,
 7, 'moderate', FALSE,
 ARRAY['romantic', 'garden', 'luxe', 'classic'],
 'Workhorse focal flower; Australian growers produce excellent David Austin varieties year-round, with peak quality Oct-Mar.'),

('spray_rose',
 'Rosa x hybrida (spray)',
 ARRAY['Spray Rose', 'Mini Rose', 'Sweetheart Rose'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[10,11,12,1,2,3], TRUE,
 'focal', ARRAY['white', 'blush', 'hot_pink', 'red', 'yellow', 'peach', 'lavender', 'orange'], 'small', 'delicate_clustered',
 'mid', 'australia_wide', FALSE,
 7, 'mild', FALSE,
 ARRAY['romantic', 'garden', 'classic', 'rustic'],
 'Multi-headed stems; excellent filler/focal hybrid. Very popular for bridal work and table centrepieces.'),

('standard_rose',
 'Rosa x hybrida',
 ARRAY['Long-stem Rose', 'Single Rose', 'Cut Rose'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[11,12,1,2,3], TRUE,
 'focal', ARRAY['red', 'white', 'pink', 'yellow', 'orange', 'purple', 'bicolor'], 'large', 'classic_cupped',
 'mid', 'australia_wide', FALSE,
 8, 'mild', FALSE,
 ARRAY['classic', 'romantic', 'luxe'],
 'Traditional single-stem rose. Available year-round from Australian and imported sources; peak quality in warmer months.'),

('peony',
 'Paeonia lactiflora',
 ARRAY['Peony', 'Chinese Peony', 'Garden Peony'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12],FALSE,
 'focal', ARRAY['white', 'blush', 'soft_pink', 'hot_pink', 'coral', 'burgundy', 'red'], 'extra_large', 'full_globe_ruffled',
 'luxury', 'australia_wide', FALSE,
 6, 'strong', FALSE,
 ARRAY['romantic', 'luxe', 'garden', 'classic'],
 'Short Australian season Oct-Dec (grown in Vic, NSW, Tas). Imported from USA/NZ extends availability. Highly sought-after for weddings.'),

('dahlia',
 'Dahlia pinnata',
 ARRAY['Dahlia', 'Café au Lait Dahlia', 'Dinner Plate Dahlia'],
 ARRAY['summer', 'autumn'], ARRAY[1,2,3,4,5], FALSE,
 'focal', ARRAY['white', 'cream', 'blush', 'peach', 'coral', 'orange', 'red', 'burgundy', 'purple', 'bicolor'], 'extra_large', 'densely_layered',
 'mid', 'australia_wide', FALSE,
 5, 'none', FALSE,
 ARRAY['garden', 'boho', 'romantic', 'rustic'],
 'Peak Jan-Apr in Australia. Locally grown; café au lait and ball varieties extremely popular for boho weddings. Short vase life — handle carefully.'),

('protea_king',
 'Protea cynaroides',
 ARRAY['King Protea', 'Giant Protea', 'King Sugar Bush'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[5,6,7,8,9,10], FALSE,
 'focal', ARRAY['blush', 'deep_pink', 'red', 'cream', 'white', 'bi_color'], 'extra_large', 'architectural_layered',
 'premium', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['native', 'modern', 'rustic', 'boho'],
 'South Africa origin, widely cultivated in WA, SA, Vic. Long vase life; ideal for statement arrangements. National flower of SA.'),

('waratah',
 'Telopea speciosissima',
 ARRAY['Waratah', 'NSW Waratah', 'Spider Flower'],
 ARRAY['spring'], ARRAY[9,10,11], FALSE,
 'focal', ARRAY['red', 'deep_crimson', 'pink', 'white'], 'large', 'bold_architectural',
 'premium', 'nsw_vic_qld', FALSE,
 10, 'none', FALSE,
 ARRAY['native', 'modern', 'rustic', 'boho'],
 'Iconic Australian native. Short spring season; premium pricing. Floral emblem of NSW. Striking architectural form.'),

('ranunculus',
 'Ranunculus asiaticus',
 ARRAY['Ranunculus', 'Persian Buttercup', 'Turban Buttercup'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10,11], FALSE,
 'focal', ARRAY['white', 'cream', 'blush', 'yellow', 'peach', 'coral', 'hot_pink', 'burgundy', 'purple'], 'medium', 'delicate_papery_layered',
 'mid', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['romantic', 'garden', 'boho', 'classic'],
 'Grown locally in Vic, SA, WA. Peak Jul-Oct. Beloved for their tissue-paper-like layers; extremely popular in wedding work.'),

('lisianthus',
 'Eustoma grandiflorum',
 ARRAY['Lisianthus', 'Prairie Gentian', 'Texas Bluebell', 'Eustoma'],
 ARRAY['spring', 'summer', 'autumn'], ARRAY[10,11,12,1,2,3,4], FALSE,
 'focal', ARRAY['white', 'cream', 'blush', 'pink', 'purple', 'lavender', 'bicolor'], 'medium', 'ruffled_cupped',
 'mid', 'australia_wide', FALSE,
 10, 'none', FALSE,
 ARRAY['romantic', 'classic', 'garden', 'boho'],
 'Often mistaken for peonies or roses. Long-lasting and locally grown. Double varieties most sought after.'),

('gerbera',
 'Gerbera jamesonii',
 ARRAY['Gerbera Daisy', 'Barberton Daisy', 'Transvaal Daisy'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2], TRUE,
 'focal', ARRAY['white', 'yellow', 'orange', 'coral', 'red', 'pink', 'burgundy', 'bi_color'], 'large', 'flat_open_radial',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['modern', 'classic', 'tropical'],
 'Widely grown across Australia; excellent value. Mini and standard forms available. Popular for casual and corporate arrangements.'),

('sunflower',
 'Helianthus annuus',
 ARRAY['Sunflower', 'Common Sunflower', 'Dwarf Sunflower'],
 ARRAY['summer', 'autumn'], ARRAY[12,1,2,3], FALSE,
 'focal', ARRAY['yellow', 'lemon', 'peach', 'rust', 'bi_color_dark_centre'], 'large', 'flat_open_textured',
 'budget', 'australia_wide', FALSE,
 7, 'mild', FALSE,
 ARRAY['rustic', 'boho', 'garden', 'tropical'],
 'Peak Dec-Mar. Widely grown in QLD, NSW, Vic. Single and double forms. Iconic summer statement flower.'),

('chrysanthemum',
 'Chrysanthemum morifolium',
 ARRAY['Mum', 'Chrysanthemum', 'Football Mum', 'Spider Mum'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[3,4,5,6,7,8], TRUE,
 'focal', ARRAY['white', 'cream', 'yellow', 'green', 'pink', 'burgundy', 'bronze', 'bi_color'], 'large', 'dense_spherical',
 'budget', 'australia_wide', FALSE,
 14, 'mild', FALSE,
 ARRAY['classic', 'modern', 'minimalist'],
 'Excellent vase life. Available year-round; peak autumn-winter. Football and spider varieties popular for modern arrangements.'),

('orchid_cymbidium',
 'Cymbidium hybrid',
 ARRAY['Cymbidium Orchid', 'Boat Orchid'],
 ARRAY['winter', 'spring'], ARRAY[6,7,8,9,10], FALSE,
 'focal', ARRAY['white', 'cream', 'green', 'pink', 'yellow', 'burgundy', 'bi_color'], 'medium', 'waxy_elegant',
 'premium', 'australia_wide', FALSE,
 21, 'none', FALSE,
 ARRAY['luxe', 'classic', 'minimalist', 'modern'],
 'Widely grown in Australia; extremely long vase life. Multi-spike stems ideal for cascading arrangements. Peak Jun-Oct.'),

('orchid_dendrobium',
 'Dendrobium phalaenopsis',
 ARRAY['Dendrobium Orchid', 'Singapore Orchid', 'Cooktown Orchid'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2], TRUE,
 'focal', ARRAY['white', 'purple', 'pink', 'green', 'bi_color'], 'small', 'delicate_arching',
 'mid', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['tropical', 'modern', 'luxe', 'minimalist'],
 'Tropical orchid grown extensively in QLD. Long-lasting multi-bloom stems. Popular for tropical and modern arrangements.'),

('anemone',
 'Anemone coronaria',
 ARRAY['Anemone', 'Poppy Anemone', 'Wind Flower'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10,11], FALSE,
 'focal', ARRAY['white', 'pink', 'red', 'purple', 'bi_color_dark_centre'], 'medium', 'open_silky_petalled',
 'mid', 'australia_wide', FALSE,
 6, 'none', FALSE,
 ARRAY['romantic', 'boho', 'garden', 'rustic'],
 'Striking dark centre. Peak Jul-Oct. Grown in SA, Vic, WA. Mix well with ranunculus for seasonal arrangements.'),

('tulip',
 'Tulipa gesneriana',
 ARRAY['Tulip', 'Dutch Tulip'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10], FALSE,
 'focal', ARRAY['white', 'cream', 'yellow', 'pink', 'red', 'orange', 'purple', 'bi_color'], 'medium', 'smooth_cupped',
 'mid', 'australia_wide', TRUE,
 5, 'none', FALSE,
 ARRAY['classic', 'romantic', 'modern', 'minimalist'],
 'Mostly imported from NZ and Netherlands. Peak Aug-Sep. Single and parrot varieties. Short vase life; keep cool.'),

('pincushion_protea',
 'Leucospermum cordifolium',
 ARRAY['Pincushion Protea', 'Nodding Pincushion', 'Leucospermum'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[5,6,7,8,9,10], FALSE,
 'focal', ARRAY['orange', 'yellow', 'red', 'coral', 'pink', 'bi_color'], 'medium', 'spiky_pincushion',
 'mid', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['native', 'rustic', 'boho', 'tropical'],
 'Grown in WA, Vic, SA. Exceptional vase life. Striking pincushion form adds texture and drama to arrangements.'),

-- ============================================================
-- FILLER FLOWERS (13)
-- ============================================================

('waxflower',
 'Chamelaucium uncinatum',
 ARRAY['Waxflower', 'Geraldton Wax', 'Geraldton Waxplant'],
 ARRAY['winter', 'spring'], ARRAY[6,7,8,9,10,11], FALSE,
 'filler', ARRAY['white', 'pink', 'hot_pink', 'purple', 'red'], 'tiny', 'delicate_waxy_clustered',
 'budget', 'australia_wide', FALSE,
 14, 'mild', FALSE,
 ARRAY['native', 'rustic', 'boho', 'garden'],
 'Australian native; WA is major producer. Exceptional vase life. Perfect filler for native-inspired bouquets and wreaths.'),

('babies_breath',
 'Gypsophila paniculata',
 ARRAY['Baby''s Breath', 'Gypsophila', 'Maiden''s Breath'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[10,11,12,1,2,3], TRUE,
 'filler', ARRAY['white', 'blush_pink'], 'tiny', 'airy_cloud_like',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['romantic', 'classic', 'garden', 'rustic'],
 'Evergreen filler staple. Australian-grown year-round. Single and double varieties. Dry beautifully for preserved work.'),

('statice',
 'Limonium sinuatum',
 ARRAY['Statice', 'Sea Lavender', 'Caspia', 'Paper Flower'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3], TRUE,
 'filler', ARRAY['purple', 'lavender', 'white', 'pink', 'yellow', 'blue'], 'tiny', 'papery_clustered',
 'budget', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['rustic', 'boho', 'garden', 'classic'],
 'Dries naturally in arrangement. Widely grown across Australia. Excellent for dried/everlasting work. Very long vase life.'),

('rice_flower',
 'Ozothamnus diosmifolius',
 ARRAY['Rice Flower', 'Sago Bush', 'White Dogwood'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10,11], FALSE,
 'filler', ARRAY['white', 'pink'], 'tiny', 'tiny_button_clustered',
 'budget', 'nsw_vic_qld', FALSE,
 10, 'mild', FALSE,
 ARRAY['native', 'rustic', 'boho', 'romantic'],
 'Eastern Australian native. Dense clusters of tiny white or pink buds. Excellent filler for native-inspired and whimsical work.'),

('flannel_flower',
 'Actinotus helianthi',
 ARRAY['Flannel Flower', 'Sydney Flannel Flower'],
 ARRAY['spring', 'summer'], ARRAY[9,10,11,12], FALSE,
 'filler', ARRAY['white', 'cream'], 'small', 'soft_flannel_textured',
 'mid', 'nsw_qld', FALSE,
 7, 'none', FALSE,
 ARRAY['native', 'boho', 'rustic', 'minimalist'],
 'Iconic NSW native. Soft grey-green felted texture; unique tactile quality. Excellent for native garden-style arrangements.'),

('boronia',
 'Boronia megastigma',
 ARRAY['Brown Boronia', 'Scented Boronia', 'Sweet Boronia'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9], FALSE,
 'filler', ARRAY['brown', 'yellow', 'pink', 'red'], 'tiny', 'bell_shaped_delicate',
 'mid', 'wa_vic', FALSE,
 5, 'strong', FALSE,
 ARRAY['native', 'rustic', 'boho'],
 'Intensely fragrant WA native. Short season Jul-Sep. Highly prized for its perfume; used sparingly for fragrant wedding work. Delicate.'),

('sweet_william',
 'Dianthus barbatus',
 ARRAY['Sweet William', 'Bearded Pink'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12,1], FALSE,
 'filler', ARRAY['red', 'pink', 'white', 'bi_color', 'burgundy'], 'small', 'dense_flat_clustered',
 'budget', 'australia_wide', FALSE,
 10, 'moderate', FALSE,
 ARRAY['garden', 'rustic', 'romantic', 'classic'],
 'Fragrant; adds texture and colour clusters. Grown across temperate Australia. Popular for cottage garden-style arrangements.'),

('nigella',
 'Nigella damascena',
 ARRAY['Nigella', 'Love-in-a-Mist', 'Devil-in-a-Bush'],
 ARRAY['spring'], ARRAY[9,10,11], FALSE,
 'filler', ARRAY['blue', 'white', 'pink', 'purple'], 'small', 'feathery_wispy',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'boho', 'rustic', 'romantic'],
 'Ethereal wispy texture. Seed pods equally beautiful for textural work. Grown locally in spring. Excellent for garden-style bouquets.'),

('scabiosa',
 'Scabiosa columbaria',
 ARRAY['Scabiosa', 'Pincushion Flower', 'Mourning Bride'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12,1,2], FALSE,
 'filler', ARRAY['white', 'lavender', 'purple', 'pink', 'pale_blue'], 'small', 'domed_pincushion',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'boho', 'romantic', 'rustic'],
 'Delicate floating appearance. Locally grown spring-summer. Pairs beautifully with ranunculus and anemone.'),

('cornflower',
 'Centaurea cyanus',
 ARRAY['Cornflower', 'Bachelor''s Button', 'Bluebottle'],
 ARRAY['spring', 'summer'], ARRAY[9,10,11,12,1], FALSE,
 'filler', ARRAY['blue', 'white', 'pink', 'purple', 'burgundy'], 'small', 'spiky_feathered',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'rustic', 'boho', 'classic'],
 'Vibrant true blue is rare in cut flowers. Grown locally spring-summer. Excellent for adding colour contrast in mixed arrangements.'),

('freesia',
 'Freesia refracta',
 ARRAY['Freesia'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10], FALSE,
 'filler', ARRAY['white', 'yellow', 'pink', 'red', 'purple', 'orange', 'bi_color'], 'small', 'arching_tubular',
 'budget', 'australia_wide', FALSE,
 7, 'strong', FALSE,
 ARRAY['classic', 'romantic', 'garden'],
 'Highly fragrant; popular for bridal posies. Grown in SA, WA, Vic. Blooms open sequentially up the stem.'),

('alstroemeria',
 'Alstroemeria aurantiaca',
 ARRAY['Alstroemeria', 'Peruvian Lily', 'Lily of the Incas'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[10,11,12,1,2,3], TRUE,
 'filler', ARRAY['white', 'yellow', 'orange', 'pink', 'red', 'purple', 'bi_color'], 'small', 'lily_like_spotted',
 'budget', 'australia_wide', FALSE,
 14, 'none', TRUE,
 ARRAY['classic', 'tropical', 'garden', 'rustic'],
 'Exceptional vase life. Widely grown across Australia. Toxic if ingested. Budget-friendly with a tropical feel.'),

('limonium',
 'Limonium latifolium',
 ARRAY['Limonium', 'Sea Lavender', 'Broad-leaf Sea Lavender'],
 ARRAY['spring', 'summer', 'autumn'], ARRAY[9,10,11,12,1,2,3,4], FALSE,
 'filler', ARRAY['lavender', 'white', 'purple', 'blue_violet'], 'tiny', 'airy_branching_cloud',
 'budget', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['rustic', 'boho', 'romantic', 'minimalist'],
 'Branching filler with tiny flowers. Dries beautifully in situ. Versatile; complements most colour palettes.'),

-- ============================================================
-- FOLIAGE (12)
-- ============================================================

('eucalyptus_silver_dollar',
 'Eucalyptus cinerea',
 ARRAY['Silver Dollar Eucalyptus', 'Argyle Apple', 'Silver Dollar Gum'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3], TRUE,
 'foliage', ARRAY['silver_grey', 'blue_green'], 'medium', 'round_silvery_leathery',
 'budget', 'australia_wide', FALSE,
 14, 'moderate', FALSE,
 ARRAY['rustic', 'boho', 'garden', 'romantic'],
 'Most popular foliage in Australian floristry. Distinctive round silver leaves and eucalyptus fragrance. Grown widely.'),

('eucalyptus_seeded',
 'Eucalyptus polyanthemos',
 ARRAY['Seeded Eucalyptus', 'Baby Blue', 'Silver Seeded Gum'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[3,4,5,6,7,8,9,10], TRUE,
 'foliage', ARRAY['silver', 'blue_grey', 'green'], 'small', 'small_round_berried',
 'budget', 'australia_wide', FALSE,
 14, 'moderate', FALSE,
 ARRAY['rustic', 'boho', 'garden', 'romantic'],
 'Seed clusters add textural interest. Extremely popular for wedding work. Long-lasting and locally sourced.'),

('eucalyptus_gunni',
 'Eucalyptus gunnii',
 ARRAY['Cider Gum', 'Gunnii Eucalyptus', 'Spinning Gum'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[1,2,3,4,5,6,7,8], TRUE,
 'foliage', ARRAY['silvery_green', 'blue_green'], 'small', 'trailing_arching_delicate',
 'budget', 'australia_wide', FALSE,
 14, 'moderate', FALSE,
 ARRAY['modern', 'minimalist', 'romantic', 'garden'],
 'Elongated, arching stems with small oval leaves. Excellent for draping and cascading bridal bouquets.'),

('gum_blossom',
 'Eucalyptus spp.',
 ARRAY['Gum Blossom', 'Eucalyptus Blossom', 'Flowering Gum'],
 ARRAY['summer', 'autumn', 'winter', 'spring'], ARRAY[11,12,1,2,3,4,5,6], FALSE,
 'foliage', ARRAY['red', 'orange', 'pink', 'white', 'cream'], 'small', 'fluffy_staminal_clusters',
 'mid', 'australia_wide', FALSE,
 7, 'moderate', FALSE,
 ARRAY['native', 'rustic', 'boho', 'tropical'],
 'The flowering stage of various eucalyptus. Fluffy pom-pom clusters highly prized in native arrangements. Varied by species.'),

('ruscus',
 'Ruscus hypophyllum',
 ARRAY['Italian Ruscus', 'Ruscus', 'Butcher''s Broom'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[1,2,3,4,5,6,7,8,9,10,11,12], TRUE,
 'foliage', ARRAY['dark_green', 'medium_green'], 'medium', 'leathery_arching_stems',
 'budget', 'australia_wide', TRUE,
 21, 'none', FALSE,
 ARRAY['classic', 'luxe', 'garden', 'romantic'],
 'Mostly imported; extremely long vase life (3+ weeks). Dark glossy leaves. Essential for hand-tied bouquets and structural greenery.'),

('pittosporum',
 'Pittosporum tenuifolium',
 ARRAY['Pittosporum', 'Black Stem Pittosporum', 'Kohuhu'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3], TRUE,
 'foliage', ARRAY['green', 'variegated_cream', 'bronze_purple'], 'small', 'wavy_edged_glossy',
 'budget', 'australia_wide', FALSE,
 14, 'mild', FALSE,
 ARRAY['garden', 'rustic', 'romantic', 'boho'],
 'Widely grown across Australia. Wavy-edged leaves on dark stems. Excellent filler foliage; slightly fragrant.'),

('maidenhair_fern',
 'Adiantum raddianum',
 ARRAY['Maidenhair Fern', 'Delta Maidenhair', 'Fern'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3,4], TRUE,
 'foliage', ARRAY['fresh_green', 'lime_green'], 'small', 'delicate_fan_shaped_lacy',
 'budget', 'australia_wide', FALSE,
 5, 'none', FALSE,
 ARRAY['romantic', 'garden', 'boho', 'rustic'],
 'Delicate lacy texture. Relatively short vase life; keep misted. Adds romantic, ethereal quality. Keep away from hot conditions.'),

('asparagus_fern',
 'Asparagus setaceus',
 ARRAY['Asparagus Fern', 'Feather Fern', 'Lace Fern'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[10,11,12,1,2,3], TRUE,
 'foliage', ARRAY['bright_green'], 'small', 'feathery_cloud_like',
 'budget', 'australia_wide', FALSE,
 10, 'none', FALSE,
 ARRAY['classic', 'romantic', 'garden'],
 'Fine feathery texture. Traditional wedding foliage. Widely grown in Australia. Excellent for softening arrangements.'),

('dusty_miller',
 'Senecio cineraria',
 ARRAY['Dusty Miller', 'Silver Dust', 'Silver Ragwort'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3], TRUE,
 'foliage', ARRAY['silver', 'grey_white'], 'medium', 'deeply_lobed_felt_textured',
 'budget', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'romantic', 'boho', 'rustic'],
 'Silver-white foliage adds cool tones and soft texture. Very popular for romantic and garden-style arrangements.'),

('olive_branch',
 'Olea europaea',
 ARRAY['Olive Branch', 'Olive Foliage'],
 ARRAY['summer', 'autumn', 'winter', 'spring'], ARRAY[2,3,4,5,6,7,8,9], TRUE,
 'foliage', ARRAY['silver_green', 'grey_green'], 'small', 'narrow_leathery_arching',
 'mid', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['rustic', 'boho', 'classic', 'minimalist'],
 'Widely grown in SA, Vic, WA. Long arching branches with silvery narrow leaves. Very popular for Mediterranean, rustic and boho weddings.'),

('monstera_leaf',
 'Monstera deliciosa',
 ARRAY['Monstera', 'Swiss Cheese Plant', 'Split-leaf Philodendron'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[11,12,1,2,3,4], TRUE,
 'foliage', ARRAY['deep_green'], 'extra_large', 'bold_tropical_fenestrated',
 'mid', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['tropical', 'modern', 'boho', 'minimalist'],
 'Tropical statement foliage. Grown commercially in QLD, NSW. Individual leaves used for tropical and modern arrangements.'),

('bear_grass',
 'Xerophyllum tenax',
 ARRAY['Bear Grass', 'Squaw Grass', 'Grass Lily'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[9,10,11,12,1,2,3], TRUE,
 'foliage', ARRAY['bright_green', 'lime_green'], 'tiny', 'long_grass_linear_arching',
 'budget', 'australia_wide', TRUE,
 14, 'none', FALSE,
 ARRAY['modern', 'minimalist', 'rustic', 'boho'],
 'Mostly imported from USA. Long arching grass-like blades. Excellent for linear arrangements and looped decorative elements.'),

-- ============================================================
-- ACCENT FLOWERS (12)
-- ============================================================

('kangaroo_paw',
 'Anigozanthos flavidus',
 ARRAY['Kangaroo Paw', 'Tall Kangaroo Paw'],
 ARRAY['spring', 'summer'], ARRAY[9,10,11,12,1,2], FALSE,
 'accent', ARRAY['red', 'yellow', 'orange', 'pink', 'green', 'bi_color'], 'medium', 'velvety_tubular_clawed',
 'mid', 'australia_wide', FALSE,
 14, 'none', FALSE,
 ARRAY['native', 'modern', 'rustic', 'tropical'],
 'Iconic WA native. Floral emblem of Western Australia. Tall structural stems with velvety textured blooms. Excellent vase life.'),

('banksia_coccinea',
 'Banksia coccinea',
 ARRAY['Scarlet Banksia', 'Waratah Banksia', 'Albany Banksia'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10], FALSE,
 'accent', ARRAY['red', 'orange_red', 'scarlet'], 'large', 'cylindrical_spiky',
 'premium', 'wa_sa', FALSE,
 21, 'none', FALSE,
 ARRAY['native', 'rustic', 'boho', 'modern'],
 'Stunning WA native with bold red cylinder cones. Exceptional vase life. Dramatic focal/accent element in native work.'),

('hypericum_berry',
 'Hypericum androsaemum',
 ARRAY['Hypericum', 'St John''s Wort Berry', 'Tutsan'],
 ARRAY['spring', 'summer', 'autumn'], ARRAY[10,11,12,1,2,3,4], FALSE,
 'accent', ARRAY['green', 'red', 'burgundy', 'peach', 'white', 'bi_color'], 'small', 'glossy_spherical_berries',
 'budget', 'australia_wide', FALSE,
 12, 'none', TRUE,
 ARRAY['rustic', 'garden', 'boho', 'classic'],
 'Glossy berry clusters add pop of colour and texture. Toxic if ingested. Very popular filler-accent. Long vase life.'),

('tweedia',
 'Tweedia caerulea',
 ARRAY['Tweedia', 'Southern Star', 'Blue Oxypetalum'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12,1], FALSE,
 'accent', ARRAY['sky_blue', 'pale_blue', 'lilac', 'white'], 'tiny', 'star_shaped_delicate',
 'mid', 'australia_wide', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'romantic', 'boho'],
 'Rare true blue in cut flowers. Grown in Qld, NSW. Unique star-shaped tiny blooms. Highly sought for blue colour palettes.'),

('blushing_bride',
 'Serruria florida',
 ARRAY['Blushing Bride', 'Serruria', 'White Serruria'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10], FALSE,
 'accent', ARRAY['white', 'blush_pink'], 'small', 'silky_layered_papery',
 'premium', 'wa_sa', FALSE,
 10, 'none', FALSE,
 ARRAY['native', 'romantic', 'boho', 'luxe'],
 'South African origin; cultivated in WA. Delicate papery blooms beloved for bridal work. National flower of South Africa.'),

('brunia',
 'Brunia albiflora',
 ARRAY['Brunia', 'Silver Brunia', 'Cape Brunia'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[5,6,7,8,9,10], FALSE,
 'accent', ARRAY['silver', 'grey', 'green_silver'], 'small', 'fuzzy_spherical_clustered',
 'mid', 'australia_wide', TRUE,
 21, 'none', FALSE,
 ARRAY['rustic', 'boho', 'modern', 'minimalist'],
 'Mostly imported from SA. Silver spherical seed-like heads; exceptional vase life. Excellent for textural contrast in modern arrangements.'),

('eryngium',
 'Eryngium planum',
 ARRAY['Eryngium', 'Sea Holly', 'Blue Thistle', 'Rattlesnake Master'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12,1,2], FALSE,
 'accent', ARRAY['steel_blue', 'purple_blue', 'silver', 'green'], 'small', 'spiky_metallic_thistle',
 'mid', 'australia_wide', TRUE,
 14, 'none', FALSE,
 ARRAY['rustic', 'modern', 'boho', 'garden'],
 'Mostly imported. Striking metallic blue spiky forms. Excellent for adding edge and texture to modern and wild arrangements.'),

('billy_buttons',
 'Craspedia globosa',
 ARRAY['Billy Buttons', 'Drumstick Flower', 'Woollyheads'],
 ARRAY['spring', 'summer'], ARRAY[9,10,11,12,1,2], FALSE,
 'accent', ARRAY['yellow', 'golden_yellow'], 'small', 'perfect_sphere_on_stem',
 'budget', 'australia_wide', FALSE,
 21, 'none', FALSE,
 ARRAY['native', 'boho', 'rustic', 'modern'],
 'Australian native; perfect golden ball on tall straight stem. Excellent fresh or dried. Very popular for boho and coastal arrangements.'),

('leucadendron',
 'Leucadendron argenteum',
 ARRAY['Leucadendron', 'Silver Tree', 'Conebush'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[4,5,6,7,8,9,10], FALSE,
 'accent', ARRAY['lime_green', 'yellow', 'red', 'burgundy', 'silver'], 'medium', 'cone_bracts_leathery',
 'mid', 'australia_wide', FALSE,
 21, 'none', FALSE,
 ARRAY['native', 'rustic', 'modern', 'boho'],
 'Grown in WA, SA, Vic. Excellent vase life. Colorful bracts around central cone; stunning natural colour range. Protea family.'),

('muscari',
 'Muscari armeniacum',
 ARRAY['Grape Hyacinth', 'Muscari', 'Armenian Grape Hyacinth'],
 ARRAY['winter', 'spring'], ARRAY[8,9,10], FALSE,
 'accent', ARRAY['purple_blue', 'cobalt_blue', 'white'], 'tiny', 'tiny_bell_clustered_spikes',
 'budget', 'australia_wide', FALSE,
 7, 'moderate', FALSE,
 ARRAY['garden', 'romantic', 'boho', 'rustic'],
 'True blue/purple colour accent. Short season Aug-Oct. Grown locally in cooler regions. Excellent for adding small pops of colour.'),

('lavender',
 'Lavandula angustifolia',
 ARRAY['Lavender', 'English Lavender', 'True Lavender'],
 ARRAY['spring', 'summer'], ARRAY[10,11,12,1], FALSE,
 'accent', ARRAY['lavender', 'purple', 'white', 'pink'], 'small', 'slender_spike_aromatic',
 'budget', 'australia_wide', FALSE,
 7, 'strong', FALSE,
 ARRAY['rustic', 'garden', 'romantic', 'boho'],
 'Grown extensively in Vic (Daylesford) and SA. Strongly fragrant; popular for bridal bundles and rustic arrangements. Dries beautifully.'),

('leucojum',
 'Leucojum aestivum',
 ARRAY['Snowflake', 'Summer Snowflake', 'Spring Snowflake'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9,10], FALSE,
 'accent', ARRAY['white_green_tip'], 'small', 'delicate_pendant_bell',
 'mid', 'vic_sa_wa', FALSE,
 7, 'none', FALSE,
 ARRAY['garden', 'romantic', 'minimalist', 'boho'],
 'Nodding white bells with green tips on arching stems. Grown in cooler regions. Delicate addition to spring arrangements.'),

-- ============================================================
-- STRUCTURAL ELEMENTS (8)
-- ============================================================

('banksia_large',
 'Banksia grandis',
 ARRAY['Bull Banksia', 'Grand Banksia', 'Banksia Cone'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[4,5,6,7,8,9,10], FALSE,
 'structural', ARRAY['golden_yellow', 'cream', 'orange_tan'], 'extra_large', 'bold_cylindrical_spiky',
 'mid', 'wa_sa', FALSE,
 21, 'none', FALSE,
 ARRAY['native', 'rustic', 'boho', 'modern'],
 'Bold statement structure. Large golden cylindrical flower spikes and distinctive serrated leaves. Excellent vase life; dries well.'),

('dried_pampas_grass',
 'Cortaderia selloana',
 ARRAY['Pampas Grass', 'Dried Pampas', 'Feather Grass'],
 ARRAY['autumn', 'winter', 'spring', 'summer'], ARRAY[3,4,5,6,7,8,9,10], TRUE,
 'structural', ARRAY['cream', 'white', 'blush_pink', 'champagne'], 'extra_large', 'fluffy_feathered_plumes',
 'mid', 'australia_wide', FALSE,
 90, 'none', FALSE,
 ARRAY['boho', 'rustic', 'modern', 'minimalist'],
 'Hugely popular for boho and dried arrangements. Grown across Australia. Long-lasting dried plumes; excellent for events and installations.'),

('cotton_stem',
 'Gossypium hirsutum',
 ARRAY['Cotton Stem', 'Cotton Boll', 'Dried Cotton'],
 ARRAY['autumn', 'winter'], ARRAY[4,5,6,7,8], FALSE,
 'structural', ARRAY['white', 'cream', 'natural'], 'small', 'fluffy_boll_on_stem',
 'mid', 'australia_wide', TRUE,
 90, 'none', FALSE,
 ARRAY['rustic', 'boho', 'modern', 'minimalist'],
 'Mostly imported from QLD cotton farms. Adds natural, tactile texture. Extremely popular for dried and winter arrangements.'),

('pussy_willow',
 'Salix discolor',
 ARRAY['Pussy Willow', 'Goat Willow', 'Catkin Willow'],
 ARRAY['winter', 'spring'], ARRAY[7,8,9], FALSE,
 'structural', ARRAY['silver_grey', 'natural'], 'small', 'soft_catkin_furry',
 'mid', 'vic_tas_nsw', TRUE,
 14, 'none', FALSE,
 ARRAY['rustic', 'garden', 'modern', 'minimalist'],
 'Soft silver catkins on arching branches. Mostly imported; some local production in cooler states. Excellent for winter and spring structural work.'),

('manzanita_branch',
 'Arctostaphylos manzanita',
 ARRAY['Manzanita Branch', 'Twisted Branch', 'Bare Branch'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[1,2,3,4,5,6,7,8,9,10,11,12], TRUE,
 'structural', ARRAY['reddish_brown', 'natural_wood'], 'extra_large', 'twisted_sculptural_bare',
 'premium', 'australia_wide', TRUE,
 365, 'none', FALSE,
 ARRAY['rustic', 'boho', 'modern', 'minimalist'],
 'Imported dried branches. Sculptural twisted forms ideal for ceremony arbours, hanging installations and statement centrepieces.'),

('protea_compacta',
 'Protea compacta',
 ARRAY['Bot River Protea', 'Compact Protea', 'Bot River Sugarbush'],
 ARRAY['autumn', 'winter', 'spring'], ARRAY[5,6,7,8,9,10], FALSE,
 'structural', ARRAY['deep_pink', 'cerise', 'cream', 'white'], 'large', 'domed_architectural_layered',
 'premium', 'wa_sa_vic', FALSE,
 21, 'none', FALSE,
 ARRAY['native', 'rustic', 'boho', 'modern'],
 'Cultivated in WA, SA. Compact dome shape; excellent as structural focal-accent hybrid. Long-lasting and dramatic.'),

('ti_tree_branch',
 'Leptospermum scoparium',
 ARRAY['Tea Tree', 'Manuka', 'New Zealand Tea Tree', 'Ti Tree'],
 ARRAY['spring', 'winter'], ARRAY[7,8,9,10,11], FALSE,
 'structural', ARRAY['white', 'pink', 'red', 'deep_pink'], 'tiny', 'twiggy_small_flowered',
 'budget', 'australia_wide', FALSE,
 7, 'mild', FALSE,
 ARRAY['native', 'rustic', 'boho', 'garden'],
 'Twiggy native branches covered in tiny flowers. Popular for adding wild, natural structure to boho arrangements and arbours.'),

('dried_banksia_pod',
 'Banksia spp.',
 ARRAY['Banksia Pod', 'Dried Banksia Cone', 'Banksia Seed Cone'],
 ARRAY['spring', 'summer', 'autumn', 'winter'], ARRAY[1,2,3,4,5,6,7,8,9,10,11,12], TRUE,
 'structural', ARRAY['brown', 'tan', 'natural', 'charcoal'], 'medium', 'rough_woody_textured_cone',
 'budget', 'australia_wide', FALSE,
 365, 'none', FALSE,
 ARRAY['native', 'rustic', 'boho', 'modern'],
 'Dried seed cones of various banksia species. Extremely long-lasting. Popular for native-inspired dried arrangements, wreaths and table decor.')

ON CONFLICT (flower_name) DO NOTHING;

-- ============================================================
-- RÉSULTAT ATTENDU
-- ============================================================
-- Cette requête ajoutera jusqu'à 62 nouvelles fleurs
-- Les 8 fleurs déjà présentes seront ignorées (ON CONFLICT DO NOTHING)
-- Total final dans la database: environ 62-70 fleurs
-- ============================================================
